name: Power BI ETL Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  format-lint-type:
    name: Format, Lint, and Type Check
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Dependencies
        run: sudo apt-get install python3-tk python3-dev

      - name: Check Formatting
        run: uv run ruff format .

      - name: Check Linting
        run: uv run ruff check .

      - name: Check Typing
        run: uv run mypy src/powerbi_etl

      - name: Run Switzerland Road Diesel ETL.
        run: xvfb-run --auto-servernum --server-num=1 uv run run_switzerland_road_diesel --environment prod

      - name: Run Cammesa Evolution ETL.
        run: xvfb-run --auto-servernum --server-num=1 uv run run_cammesa_etl --environment prod
